services:
  Vaszev\HandyBundle\Service\Handy:
    public: false
    autowire: true
    autoconfigure: true
    arguments: ["@security.command.user_password_encoder"]

  Vaszev\HandyBundle\Service\MyRedis:
    public: false
    autowire: true
    autoconfigure: true
    arguments: ["@service_container","@security.token_storage"]

  Vaszev\HandyBundle\Twig\HandyExtension:
    public: false
    autowire: true
    autoconfigure: true
#    arguments: ["@Vaszev\HandyBundle\Service\Handy""@service_container"]
