services:
  Vaszev\HandyBundle\Service\Handy:
    public: false
    autowire: true
    autoconfigure: true
    arguments: ["@security.command.user_password_encoder"]

  Vaszev\HandyBundle\Service\MyRedis:
    public: false
    autowire: true
    autoconfigure: true

  Vaszev\HandyBundle\Twig\HandyExtension:
    public: false
    autowire: true
    autoconfigure: true
